name: deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  gas-files:
    name: Prepare gas files
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lobis/gas-cli:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Uncompress Garfield gas files using python script
        run: |
          python scripts/uncompress.py

      - name: Remove compressed files
        run: |
          find ./files -type f -name *.tar.gz -exec rm {} \;

      - name: Move into public directory
        run: |
          mv files/ public/

      - name: Cache gas files
        uses: actions/cache@v3
        id: cache
        with:
          key: gas-files-${{ github.run_id }}
          path: public/

      - name: Upload gas files artifact
        uses: actions/upload-artifact@v3
        with:
          name: gas-files
          path: public/

  deploy: # https://github.com/actions/deploy-pages
    name: GitHub Pages deployment
    runs-on: ubuntu-latest
    needs: gas-files

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
